Update udocker.py
At some systems '--delay-directory-restore' is not available. In that case, import of the exported image ends up with:

Error: failed to extract container: image.tar
Error: loading failed 

After looking into udocker.py it turned out that issue is here:

tar: unrecognized option `--delay-directory-restore'
Try `tar --help' or `tar --usage' for more information.